coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 5%
      flutter:
        target: 100%
        threshold: 5%
    patch:
      default:
        target: 100%
        threshold: 5%