# Tutorial: CI/CD for Flutter is a piece of cake with fastlane and Codemagic
# https://blog.codemagic.io/ci-cd-for-flutter-with-fastlane-codemagic/

# Format Ruby File: rubocop --auto-correct your_file.rb

import './lanes/TestLanes.rb'
import './lanes/ReleaseLanes.rb'